= Real-World Active Directory Case Studies: GOAD and Community Benchmarks

<ch:case_study>

== From Synthetic Topologies to Enterprise Deployments

While controlled synthetic environments provide the mathematical foundation necessary to train neural architectures and isolate experimental variables, enterprise cybersecurity requires models to generalize seamlessly to real, messy, production-grade operating systems. Real-world Active Directory deployments exhibit structural idiosyncrasies that rarely appear in idealized synthetic generators:

+ Multi-forest trust topologies with complex Kerberos referral tickets and SID filtering boundaries.
+ Highly nested security group hierarchies created over decades of administrative churn.
+ Legacy access control entries (ACEs) inheriting permissions across deep Organizational Unit (OU) trees.
+ Partial or noisy directory collections caused by network timeouts, firewall packet filtering, and endpoint sensor coverage gaps.



To establish whether CertGraph generalizes beyond synthetic graphs to real Windows enterprise infrastructures, we deployed our evaluation framework against the *Game of Active Directory (GOAD)* @garla2020game testbed, followed by multi-week temporal validation and external community-collected enterprise datasets.

== The Game of Active Directory (GOAD) Multi-Forest Testbed

GOAD is an acclaimed, widely recognized vulnerable enterprise research environment deployed on dedicated virtualization hardware. The infrastructure mirrors the complex identity architecture of a multi-national conglomerate spanning five dedicated virtual machines running licensed Windows Server 2016, Windows Server 2019, and Windows 10 Enterprise operating systems:


+ *`sevenkingdoms.local` (Parent Root Domain):* Hosted on Domain Controller `kingslanding.sevenkingdoms.local` (Windows Server 2019). Manages 16 human user accounts, 59 global and universal security groups, Enterprise Certificate Services infrastructure, and authoritative Tier-0 administrative roles (`Enterprise Admins`, `Schema Admins`).
+ *`north.sevenkingdoms.local` (Child Domain):* Operates in a bidirectional transitive parent-child domain trust with the parent domain. Hosted across two dedicated systems: Primary Domain Controller `winterfell.north.sevenkingdoms.local` (Windows Server 2019) and secondary enterprise server `castelblack.north.sevenkingdoms.local` (Windows Server 2016). Manages 5 regional user accounts and 47 security groups.
+ *`essos.local` (External Forest):* An independent corporate forest connected to `sevenkingdoms.local` via a one-way, non-transitive external forest trust with selective authentication and SID filtering. Hosted on Domain Controller `braavos.essos.local` (Windows Server 2019) and workstation client `meereen.essos.local` (Windows 10). Manages 14 user accounts and 60 security groups.



As illustrated in @fig:goad_topology, the multi-forest architecture features interconnected parent, child, and external domains. Of critical operational relevance to this thesis, the Enterprise Certificate Authority (`ADCS - ESSOS-CA`) is hosted on `SRV03 - braavos`, representing an authentic enterprise PKI target accessible via both LDAP enrollment and cross-domain authentication links.

#figure(
  image("figures/goad_forest_topology.png", width: 90%),
  caption: [Architecture and trust relationship schema of the Game of Active Directory (GOAD) multi-forest lab environment, detailing domain controllers, member servers (including the ADCS Certificate Authority `SRV03 - braavos`), and cross-forest authentication links.],
) <fig:goad_topology>


== Data Ingestion, Extraction, and Schema Translation

To bridge live Windows domain controllers and our PyTorch Geometric deep learning pipeline, we engineered an automated data ingestion and schema translation engine implemented in `bloodhound_parser.py`.

=== Active Directory Telemetry Collection

Data collection against the live GOAD virtual machines was conducted using the SharpHound v5 collector executed from unprivileged domain accounts. SharpHound queries the Active Directory Global Catalog via LDAP (TCP 389/636), Active Directory Web Services (TCP 9389), and NetBIOS/SMB (TCP 445), extracting:

+ Security Principal metadata (Users, Computers, Groups, CAs, Templates).
+ Group membership nesting hierarchies (`MemberOf`).
+ Active user logon sessions via NetSessionEnum and Remote Registry APIs.
+ Full Discretionary Access Control Lists (DACLs) from directory security descriptors.
+ Certificate template attributes and Enterprise CA enrollment publication lists.



=== Graph Schema Translation Pipeline

The raw JSON data structures generated by SharpHound were ingested and converted into PyTorch Geometric `HeteroData` tensors via a four-stage translation process:

+ *Identity and SID Disambiguation:* Windows Security Identifiers (e.g., `S-1-5-21-123456789-500`) and Distinguished Names (DNs) are mapped to contiguous 0-indexed integer identifiers within disjoint typed node partitions ($V_("User")$, $V_("Computer")$, $V_("Group")$, $V_("Template")$, $V_("CA")$).
+ *Attribute Vectorization:* LDAP property dictionaries are parsed to extract binary feature vectors. Certificate template flags (`msPKI-Certificate-Name-Flag`, `pKIExtendedKeyUsage`, `msPKI-Certificate-Policy`) are converted into the 10-dimensional template feature vector $x_("Template") in bb(R)^(10)$.
+ *Relational Edge Mapping:* Active Directory Access Control Entries (ACEs) and enrollment permissions are categorized into canonical directed relation tensors ($E_("MemberOf")$, $E_("Enroll")$, $E_("GenericAll")$, $E_("WriteDacl")$, $E_("WriteOwner")$, $E_("PublishedTo")$, $E_("ManageCA")$, $E_("LinksPolicy")$).
+ *Reverse Canonical Relation Generation:* For every extracted directed edge tensor $E_r$, the transposed edge tensor $E_(r^(-1)) = {(v, r^(-1), u) | (u, r, v) in E_r}$ is generated to facilitate bidirectional relational message passing.



== Concrete Penetration Testing Case Studies

To evaluate CertGraph against traditional signature-based auditing tools (Certipy) on real Windows enterprise topologies, we deployed 10 representative certificate template configurations across the GOAD domain structures. These configurations encompass standard attack vectors, novel misconfigurations, and challenging hard negative scenarios:

#figure(
  text(size: 8pt)[
  #table(
    columns: (1.5fr, 1fr, 1fr, 1fr, 2fr),
    stroke: (x, y) => if y == 0 { (top: 1.2pt + luma(0), bottom: 0.8pt + luma(0)) } else if y == 1 { (bottom: 0.8pt + luma(0)) } else if y == 11 { (bottom: 1.2pt + luma(0)) } else { none },
    inset: (x: 4pt, y: 3.8pt),
    table.header([*Case Scenario*], [*Ground Truth*], [*Certipy*], [*CertGraph*], [*Operational Security Outcome*]),
    [`ESC1_Standard`], [ESC1], [ESC1], [ESC1], [True Positive (Both Correct)],
    [`ESC2_AnyPurpose`], [ESC2], [ESC2], [ESC2], [True Positive (Both Correct)],
    [`ESC3_Agent`], [ESC3], [ESC3], [ESC3], [True Positive (Both Correct)],
    [`ESC4_DACL_Abuse`], [ESC4], [ESC4], [ESC4], [True Positive (Both Correct)],
    [`ESC9_NoPAC`], [ESC9], [ESC9], [ESC9], [True Positive (Both Correct)],
    [`ESC13_PolicyLink`], [ESC13], [Safe (Missed)], [ESC13], [*CertGraph Discovers Novel Vector*],
    [`HN_ESC1 (Hard Neg.)`], [Safe], [ESC1 (FP)], [Safe], [*CertGraph Suppresses False Alarm*],
    [`HN_ESC4 (Hard Neg.)`], [Safe], [ESC4 (FP)], [Safe], [*CertGraph Suppresses False Alarm*],
    [`HN_ESC13 (Hard Neg.)`], [Safe], [Safe], [Safe], [True Negative (Both Correct)],
    [`Benign_Template`], [Safe], [Safe], [Safe], [True Negative (Both Correct)],
  )
],
  caption: [Comparative Auditing Performance on Live Ingested GOAD Topologies.],
) <tab:goad_results>


=== Detailed Case Study Analysis

*Case 1: Discovery of Novel Vector (ESC13).*
In the `ESC13_PolicyLink` scenario, the template was configured with an Issuance Policy OID linked directly to the `Enterprise Admins` group in `sevenkingdoms.local`. 

+ *Certipy Failure:* Standard Certipy heuristic rules failed to detect the vulnerability, reporting the template as completely benign. This occurred because Certipy's static signature engine evaluated templates in isolation and lacked logic to resolve `msPKI-Certificate-Policy` LDAP references.
+ *CertGraph Detection:* CertGraph correctly identified the vulnerability as `ESC13`, tracing the 2-hop composite path: $ "User" limits(arrow.r)^("Enroll)" "Template" limits(arrow.r)^("LinksPolicy)" "Enterprise Admins" $ The relational attention mechanism assigned high attention coefficients ($alpha > 0.88$) to the policy link, proving the model's capacity to discover relational misconfigurations that elude static rule-based scanners.



*Case 2: False Positive Suppression on Hard Negatives (HN_ESC1 and HN_ESC4).*
In scenario `HN_ESC1`, a template was configured with the dangerous flag `CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT` enabled alongside Client Authentication EKUs, but its Discretionary Access Control List strictly restricted enrollment permissions to members of `Domain Admins`.

+ *Certipy False Alarm:* Certipy flagged the template as a *Critical ESC1 Privilege Escalation Vulnerability*, generating an urgent security alert. Because Certipy inspects configuration flags without verifying unprivileged graph reachability, it could not determine whether an attacker could actually invoke the template.
+ *CertGraph Accurate Assessment:* CertGraph evaluated the template as *`Safe`*, recognizing that the incoming enrollment edges originated exclusively from nodes where $f_("is_admin") = 1.0$. By jointly evaluating configuration attributes and authorization topology, CertGraph successfully eliminated alert fatigue.



The full complexity of transitive compromise chains across GOAD is visualized in @fig:goad_paths. From unprivileged workstations and compromised user credentials, adversaries execute multi-stage attacks chaining Kerberoasting, NTLM relaying, and ADCS misconfigurations (ESC1, ESC2, ESC3, ESC6, ESC8) to cross domain trusts and compromise root enterprise domain controllers.

#figure(
  image("figures/goad_attack_paths.png", width: 90%),
  caption: [End-to-end multi-hop compromise and privilege escalation attack graph across the GOAD domain infrastructure, illustrating how unprivileged foothold credentials traverse ADCS certificate misconfigurations (ESC1--ESC8), Kerberos delegations, and inter-domain trusts to achieve enterprise domain dominance.],
) <fig:goad_paths>


== Temporal Validation Across Independent Collection Dates

A major vulnerability in machine learning evaluations is sensitivity to temporal environmental drift and collection artifacts. In operational enterprise environments, Active Directory graphs mutate continuously as users log on, temporary sessions expire, and security groups are modified.

To establish whether CertGraph maintains stable representations over time, we conducted three independent data collections against the running GOAD virtual machines across distinct calendar dates:

+ *Collection Baseline (T1):* June 15, 2026.
+ *Follow-up Snapshot (T2):* July 2, 2026 (17 days later, following intermediate red-team simulation exercises).
+ *Validation Snapshot (T3):* August 10, 2026 (56 days later, following system patching and host reboots).



CertGraph (trained exclusively on synthetic data) was evaluated zero-shot against all three temporal snapshots without fine-tuning:

+ `sevenkingdoms.local`: $7 / 7$ test cases correctly classified across all dates ($100.0%$).
+ `north.sevenkingdoms.local`: $7 / 7$ test cases correctly classified across all dates ($100.0%$).
+ `essos.local`: $7 / 7$ test cases correctly classified across all dates ($100.0%$).
+ *Aggregate Temporal Accuracy:* $bold(63 / 63)$ test cases correctly classified ($bold(100.0%)$).


This multi-week temporal validation confirms that CertGraph's learned relational representations are invariant to transient session noise and background administrative churn.

== External Community Benchmark Validation

To eliminate dataset collection bias and verify model robustness on telemetry collected outside our local virtualization lab, we evaluated CertGraph against an independent open-source enterprise dataset from the `m4lwhere/Bloodhound-CE-Sample-Data` repository. This repository contains raw SharpHound telemetry collected from an external, multi-domain GOADv2 installation managed by independent security researchers.

#figure(
  text(size: 9.5pt)[
  #table(
    columns: (1.5fr, 1fr, 1fr, 1fr, 2fr),
    stroke: (x, y) => if y == 0 { (top: 1.2pt + luma(0), bottom: 0.8pt + luma(0)) } else if y == 1 { (bottom: 0.8pt + luma(0)) } else if y == 5 { (bottom: 1.2pt + luma(0)) } else { none },
    inset: (x: 4pt, y: 3.8pt),
    table.header([*External Domain*], [*Test Cases*], [*Certipy Accuracy*], [*CertGraph Accuracy*], [*Performance Gain*]),
    [`sevenkingdoms`], [10], [$70.0%$ (7 / 10)], [$bold(100.0%)$ (10 / 10)], [$+30.0%$],
    [`essos`], [10], [$60.0%$ (6 / 10)], [$bold(100.0%)$ (10 / 10)], [$+40.0%$],
    [`north`], [10], [$60.0%$ (6 / 10)], [$bold(100.0%)$ (10 / 10)], [$+40.0%$],
    [*Aggregate Average*], [*30*], [$bold(63.3%)$ (19 / 30)], [$bold(100.0%)$ (30 / 30)], [$bold(+36.7%)$],
  )
],
  caption: [Classification Accuracy on External Community-Collected Enterprise Topologies.],
) <tab:community_results>


As shown in @tab:community_results, across 30 test scenarios spanning the three external enterprise domains, CertGraph maintained a perfect *100.0% accuracy*, whereas signature-based heuristics averaged only *63.3%*. The performance gain of $+36.7%$ was driven by CertGraph's ability to discover relational vectors (such as ESC13) and suppress false positives on hardened templates. This validates that CertGraph's relational representations transfer seamlessly across independent enterprise directory collections.
